org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = fi.dy.masa
mod_id = servux
mod_name = Servux
author = masa
mod_file_name = servux-fabric

# Current mod version
mod_version = 0.11.3+lan-supported

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 26.2
minecraft_version = 26.2

fabric_loader_version = 0.19.3
fabric_api_version = 0.154.0+26.2

# Luck Permissions API (https://github.com/lucko/fabric-permissions-api)
fabric_permissions_api_version = 0.7.0

condition_mixin_version = 0.6.4